# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Paws4Me' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Paws4Me
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  target 'Paws4MeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Paws4MeUITests' do
    # Pods for testing
  end

end
